# Generated by Django 5.2.1 on 2025-05-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Номер ВУ')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип транспортного средства',
                'verbose_name_plural': 'Типы транспортных средств',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Госномер')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('in_repair', 'В ремонте'), ('retired', 'Списан'), ('idle', 'Простаивает')], default='active', max_length=50, verbose_name='Статус')),
                ('acquisition_date', models.DateField(verbose_name='Дата приобретения')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Пробег (км)')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.driver', verbose_name='Назначенный водитель')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicletype', verbose_name='Тип ТС')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('record_type', models.CharField(choices=[('maintenance', 'Техническое обслуживание'), ('repair', 'Ремонт'), ('inspection', 'Осмотр')], max_length=50, verbose_name='Тип записи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='transport.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Запись о ТО/Ремонте',
                'verbose_name_plural': 'Записи о ТО/Ремонте',
                'ordering': ['-date'],
            },
        ),
    ]
